apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${serviceName}-${environment}-queue-worker-high
  namespace: ${environment}-${serviceName}
  labels:
    tier: backend
    layer: queue-worker
    queue: high
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      layer: queue-worker
      queue: high
  template:
    metadata:
      labels:
        tier: backend
        layer: queue-worker
        queue: high
    spec:
      containers:
        - name: queue-worker
          image: ${DOCKER_REGISTRY}/${serviceName}_cron:v${imageVersion}
          command:
            - php
          args:
            - artisan
            - queue:work
            - --queue=high
            - --verbose
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: ${serviceName}
            - secretRef:
                name: ${serviceName}
